"""SDK-facing endpoints: assignments, traces, spans, outcomes."""
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession
from coii_server.db import get_db
from coii_server.activities import SDKActivity

router = APIRouter()


class TraceCreate(BaseModel):
    id: str  # public_id generated by SDK
    user_id: str
    session_id: Optional[str] = None
    name: Optional[str] = None
    metadata: dict = {}


class SpanCreate(BaseModel):
    trace_id: str  # trace public_id
    type: str
    latency_ms: int
    model: Optional[str] = None
    input_tokens: Optional[int] = None
    output_tokens: Optional[int] = None
    name: Optional[str] = None
    status: str = "success"
    metadata: dict = {}


class OutcomeCreate(BaseModel):
    user_id: str
    event_name: str
    properties: dict = {}


class TraceEnd(BaseModel):
    trace_id: str


@router.get("/assignments")
async def get_assignments(user_id: str, db: AsyncSession = Depends(get_db)):
    activity = SDKActivity(db)
    r = await activity.get_assignments(user_id)
    return r.value


@router.get("/user-assignment")
async def get_user_assignment(
    user_id: str,
    experiment_name: str,
    db: AsyncSession = Depends(get_db),
):
    """Look up which variant a specific user is assigned to in an experiment."""
    from sqlalchemy import select, and_
    from coii_server.models.orm import Experiment, Exposure

    exp = await db.scalar(select(Experiment).where(Experiment.name == experiment_name))
    if not exp:
        raise HTTPException(404, f"Experiment '{experiment_name}' not found")

    exposure = await db.scalar(
        select(Exposure).where(
            and_(Exposure.experiment_id == exp.id, Exposure.user_id == user_id)
        )
    )
    if not exposure:
        return {"user_id": user_id, "experiment": experiment_name, "assigned": False, "variant": None}

    variant_config = next(
        (v for v in exp.variants if v["name"] == exposure.variant_name), None
    )
    return {
        "user_id": user_id,
        "experiment": experiment_name,
        "assigned": True,
        "variant": exposure.variant_name,
        "variant_config": variant_config,
        "exposure_id": exposure.public_id,
        "exposed_at": exposure.exposed_at.isoformat(),
    }


@router.post("/traces", status_code=201)
async def create_trace(body: TraceCreate, db: AsyncSession = Depends(get_db)):
    activity = SDKActivity(db)
    r = await activity.create_trace(
        public_id=body.id,
        user_id=body.user_id,
        session_id=body.session_id,
        name=body.name,
        metadata=body.metadata,
    )
    if not r.ok:
        raise HTTPException(400, r.message)
    t = r.value
    return {"id": t.public_id, "user_id": t.user_id}


@router.patch("/traces/{trace_id}/end")
async def end_trace(trace_id: str, db: AsyncSession = Depends(get_db)):
    activity = SDKActivity(db)
    r = await activity.end_trace(trace_id)
    if not r.ok:
        raise HTTPException(404, r.message)
    return {"id": r.value.public_id, "ended_at": r.value.ended_at.isoformat()}


@router.post("/spans", status_code=201)
async def create_span(body: SpanCreate, db: AsyncSession = Depends(get_db)):
    activity = SDKActivity(db)
    r = await activity.create_span(
        trace_public_id=body.trace_id,
        type=body.type,
        latency_ms=body.latency_ms,
        model=body.model,
        input_tokens=body.input_tokens,
        output_tokens=body.output_tokens,
        name=body.name,
        status=body.status,
        metadata=body.metadata,
    )
    if not r.ok:
        raise HTTPException(404 if r.code == "NOT_FOUND" else 400, r.message)
    s = r.value
    return {
        "id": s.public_id,
        "trace_id": body.trace_id,
        "cost_usd": float(s.cost_usd) if s.cost_usd is not None else None,
    }


@router.post("/outcomes", status_code=201)
async def record_outcome(body: OutcomeCreate, db: AsyncSession = Depends(get_db)):
    activity = SDKActivity(db)
    r = await activity.record_outcome(
        user_id=body.user_id,
        event_name=body.event_name,
        properties=body.properties,
    )
    if not r.ok:
        raise HTTPException(400, r.message)
    o = r.value
    return {"id": o.public_id, "user_id": o.user_id, "event_name": o.event_name}
